config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/apricotlab:
      branch: main
      repo: https://github.com/grycap/apricotlab
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_polite_grasshopper.sh
        container: qc.acc_fog_friendly_fox
  QC.Doc:
    repos:
      github.com/grycap/apricotlab find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crimson_rugged_swan.sh
        container: qc.doc_mauve_content_gorilla
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.fuchsia_zany_boa.sh
        container: qc.doc_vermilion_honest_viper
      github.com/grycap/apricotlab markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.rosewater_organized_rhinoceros.sh
        container: qc.doc_forest_graceful_flamingo
  QC.Lic:
    repos:
      github.com/grycap/apricotlab licensee:
        commands:
        - /usr/bin/env sh .sqa/script.mint_lucky_spren.sh
        container: qc.lic_vermilion_clever_salamander
  QC.Met:
    repos:
      github.com/grycap/apricotlab validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.isabelline_playful_caiman.sh
        container: qc.met_tide_generous_impala
  QC.Sec:
    repos:
      github.com/grycap/apricotlab bandit:
        commands:
        - /usr/bin/env sh .sqa/script.brown_imaginative_quoll.sh
        container: qc.sec_daffodil_mischievous_emu
  QC.Sty:
    repos:
      github.com/grycap/apricotlab flake8:
        commands:
        - /usr/bin/env sh .sqa/script.persimmon_calm_crane.sh
        container: qc.sty_gamboge_attentive_iguana
      github.com/grycap/apricotlab hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cloud_dreamy_komodo.sh
        container: qc.sty_cinnabar_practical_condor
      github.com/grycap/apricotlab jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sand_impulsive_flounder.sh
        container: qc.sty_claret_practical_dolphin
      github.com/grycap/apricotlab pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.linen_playful_jellyfish.sh
        container: qc.sty_gunmetal_trustworthy_sloth
  QC.Uni:
    repos:
      github.com/grycap/apricotlab pytest:
        commands:
        - /usr/bin/env sh .sqa/script.green_proactive_cobra.sh
        container: qc.uni_denim_fearless_ocelot
  QC.Ver:
    repos:
      github.com/grycap/apricotlab get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ash_aware_coyote.sh
        container: qc.ver_purple_dramatic_salamander
timeout: 5400
