config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/apricotlab:
      branch: main
      repo: https://github.com/grycap/apricotlab/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-indigo-duck.sh
        container: qc.acc_frumpy-green-butterfly
  QC.Doc:
    repos:
      github.com/grycap/apricotlab find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-lilac-llama.sh
        container: qc.doc_leaky-celadon-barnacle
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-yellow-stingray.sh
        container: qc.doc_foggy-olivine-cassowary
      github.com/grycap/apricotlab markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-champagne-snail.sh
        container: qc.doc_wiggy-bistre-newt
  QC.Lic:
    repos:
      github.com/grycap/apricotlab licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ecru-chinchilla.sh
        container: qc.lic_lumpy-green-argentino
  QC.Met:
    repos:
      github.com/grycap/apricotlab validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-denim-antelope.sh
        container: qc.met_pretty-corn-lobster
  QC.Sec:
    repos:
      github.com/grycap/apricotlab bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aqua-butterfly.sh
        container: qc.sec_cheeky-aqua-camel
  QC.Sty:
    repos:
      github.com/grycap/apricotlab flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pumpkin-jackal.sh
        container: qc.sty_skinny-green-dolphin
      github.com/grycap/apricotlab hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ivory-tang.sh
        container: qc.sty_bumpy-crimson-swan
      github.com/grycap/apricotlab jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-carmine-eleuth.sh
        container: qc.sty_woolly-lime-uguisu
      github.com/grycap/apricotlab pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-persimmon-mouse.sh
        container: qc.sty_jumpy-cardinal-bombay
  QC.Uni:
    repos:
      github.com/grycap/apricotlab pytest:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-magnolia-mammoth.sh
        container: qc.uni_trippy-peach-dane
  QC.Ver:
    repos:
      github.com/grycap/apricotlab get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mustard-sheep.sh
        container: qc.ver_frumpy-amaranth-uakari
timeout: 5400
