config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/apricotlab:
      branch: main
      repo: https://github.com/grycap/apricotlab/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_spirited_gull.sh
        container: qc.acc_pumpkin_outgoing_mink
  QC.Doc:
    repos:
      github.com/grycap/apricotlab find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scarlet_sincere_angelfish.sh
        container: qc.doc_copper_blissful_crocodile
      github.com/grycap/apricotlab git:
        commands:
        - /usr/bin/env sh .sqa/script.byzantium_supportive_eagle.sh
        container: qc.doc_ochre_patient_moose
      github.com/grycap/apricotlab markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_spontaneous_seal.sh
        container: qc.doc_celadon_delighted_lemur
  QC.Lic:
    repos:
      github.com/grycap/apricotlab licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pearl_imaginative_seal.sh
        container: qc.lic_wine_shy_lynx
  QC.Met:
    repos:
      github.com/grycap/apricotlab validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gray_lively_mandrill.sh
        container: qc.met_pink_happy_horse
  QC.Sec:
    repos:
      github.com/grycap/apricotlab bandit:
        commands:
        - /usr/bin/env sh .sqa/script.echelon_fair_raccoon.sh
        container: qc.sec_pumpkin_rustic_antelope
  QC.Sty:
    repos:
      github.com/grycap/apricotlab flake8:
        commands:
        - /usr/bin/env sh .sqa/script.mist_nervous_rhinoceros.sh
        container: qc.sty_lagoon_brilliant_frog
      github.com/grycap/apricotlab hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_dizzy_roadrunner.sh
        container: qc.sty_reef_jubilant_manatee
      github.com/grycap/apricotlab jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tide_cautious_hornbill.sh
        container: qc.sty_wisteria_quirky_boa
      github.com/grycap/apricotlab pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_stubborn_cougar.sh
        container: qc.sty_plum_quirky_python
  QC.Uni:
    repos:
      github.com/grycap/apricotlab pytest:
        commands:
        - /usr/bin/env sh .sqa/script.powder_tranquil_otter.sh
        container: qc.uni_orange_ambitious_kookaburra
  QC.Ver:
    repos:
      github.com/grycap/apricotlab get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.coral_dizzy_gibbon.sh
        container: qc.ver_navy_blissful_parrot
timeout: 5400
